[package]
name = "kaleidoscope"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llvm-sys = "130"
scopeguard = "1.1.*"

[dev-dependencies]
pretty_assertions = { version = "1.0.0" }
