name: Install LLVM

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      directory:
        required: true
        type: string

jobs:
  install-llvm:
    runs-on: ubuntu-latest

    steps:
    - name: Cache LLVM and Clang
      id: cache-llvm
      uses: actions/cache@v2
      with:
        path: ${{ inputs.directory }}
        key: ${{ inputs.version }}
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: ${{ inputs.version }}
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}

