name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  install_llvm:
    uses: ./.github/workflows/install_llvm.yml
    with:
      version: "13.0"
      directory: "home/runner/work/llvm"

  build:
    needs: install_llvm
    runs-on: ubuntu-latest

    steps:
    - name: Git Config
      run: git config --global init.defaultBranch main
    - uses: actions/checkout@v2
    - name: List Files
      run: ls home/runner/work/llvm"
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  clippy_check:
    needs: install_llvm
    uses: ./.github/workflows/clippy_check.yml
