name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  LLVM_INSTALL_DIR: "~/llvm"
  LLVM_INSTALL_VERSION: "13.0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git Config
      run: git config --global init.defaultBranch main
    - name: Cache LLVM and Clang
      id: cache-llvm
      uses: actions/cache@v2
      with:
        path: $LLVM_INSTALL_DIR
        key: $LLVM_INSTALL_VERSION
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: $LLVM_INSTALL_VERSION
        directory: $LLVM_INSTALL_DIR
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          components: clippy
          override: true
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
